# Generated by Django 5.2.8 on 2025-11-11 10:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault_auth', '0002_passwordrequest_otp_passwordrequest_otp_expires_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordViewLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('password_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_logs', to='vault_auth.passwordentry')),
                ('viewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Password View Log',
                'verbose_name_plural': 'Password View Logs',
                'db_table': 'password_view_logs',
                'ordering': ['-viewed_at'],
            },
        ),
    ]
