# Generated by Django 5.2.8 on 2025-11-16 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vault_auth', '0003_passwordviewlog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='passwordentry',
            options={'ordering': ['-created_at'], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterModelTable(
            name='passwordentry',
            table='vault_auth_user',
        ),
    ]
